"""added like count

Revision ID: eeef61b201fb
Revises: 341e5d03520d
Create Date: 2023-12-11 17:07:09.796509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeef61b201fb'
down_revision = '341e5d03520d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
